#!/usr/bin/env python
import sys
import os
from twython import Twython
import random
import datetime
import time

#Define API keys
CONSUMER_KEY = ''
CONSUMER_SECRET = ''
ACCESS_KEY = ''
ACCESS_SECRET = ''

#Create a copy of the Twython object with all our keys and secrets to allow easy commands.
api = Twython(CONSUMER_KEY,CONSUMER_SECRET,ACCESS_KEY,ACCESS_SECRET)

print("DTA_Bot connected")

#get date
fulldate = datetime.datetime.utcnow().strftime("%Y/%m/%d")
year = datetime.datetime.utcnow().strftime("%Y")
month = datetime.datetime.utcnow().strftime("%m")
day = datetime.datetime.utcnow().strftime("%d")
yday = int(day) - 1
temp = int(day)
if temp <= 9:
    yday = str(yday)
    yday = "0"+yday

fave_counter = 0
rt_counter = 0

number = 50
while number > 5:    
    fave_counter = fave_counter + 5000
    rt_counter = rt_counter + 5000  

    query = "min_faves:" +str(fave_counter) + " min_retweets:" + str(rt_counter) + " until:" + str(year) + "-" + str(month) + "-" + str(day) + " since:" + str(year) + "-" + str(month) + "-" + str(yday) + " -filter:links -filter:replies"

    search = api.search(q=query)
    results = search['statuses']
    number = len(results)
    print("This search returned " + str(number) + " results")

champion = 0
if number > 1:
    for tweet in results:
        print("")
        print("Assessing popularity score...")
        faves = tweet['favorite_count']
        RTs = tweet['retweet_count']
        tweetid = tweet['id']
        total = int(faves) + int(RTs)
        verified = tweet['user']['verified']
        if verified == True:
            total = total * 0.75
        if total > champion:
            print("New champion crowned!")
            winner = tweetid
            user = tweet['user']['screen_name']
        else:
            continue
else:
    tweetid = results[0]('id')
    user = results[0]['user']['screen_name']


y = int(year)
m = int(month)
d = int(day)
d = d - 1
date = datetime.datetime(y, m, d)
date = (date.strftime("%b %d %Y"))


string = "Congratulations @" + str(user) +"\n" + "This tweet of yours was the most popular tweet of " + str(date) + "\n" + "It reached a combined RT + Like count of " + str(total) + "!"
api.update_status(status=string, in_reply_to_status_id =tweetid)
print(string)
